name: junitreport
version: 2.0.3-dev
description: Generate JUnit XML reports from dart test runs. Transforms the output of dart or flutter tests to
  JUnit style XML

homepage: https://github.com/TOPdesk/dart-junitreport
documentation:

dependencies:
  args: 2.6.0
  intl: 0.20.1
  testreport: 2.0.1
  xml: 6.5.0

dev_dependencies:
  test: any
  lints: 5.1.1

environment:
  sdk: '>=3.0.0 <4.0.0'

executables:
  tojunit: